### ISSUE TITLE
Netherlands - separating postcode into postcode & road

### ISSUE THREAD

**Issue by mkaranta** [openvenues/libpostal#195]
I've encountered an issue with parsing addresses from the Netherlands. Their postalcodes are usually of the form `"DDDD XX"`, where D is a digit and X is an alpha [(source)](http://www.postadressglobal.com/country/netherlands/formatting-and-structure-of-dutch-addresses/). 

Libpostal seems to classify the 2 suffix characters as a road.

```
 Easterboarn 11, 8495 NB Aldeboarn, Netherlands

Result:

{
  "road": "easterboarn",
  "house_number": "11",
  "postcode": "8495",
  "road": "nb",
  "city": "aldeboarn",
  "country": "netherlands"
}
```

This is consistent across my (small) test suite of 8,000 NL addresses.

**Comment by thatdatabaseguy** [comment]
We train on virtually every address in the Netherlands but I'm pretty sure the format used both in OSM and our Netherlands countrywide data set from OpenAddresses is "8495NB" with no space, so that's essentially the only form libpostal knows.

```
> Easterboarn 11, 8495NB Aldeboarn, Netherlands

Result:

{
  "road": "easterboarn",
  "house_number": "11",
  "postcode": "8495nb",
  "city": "aldeboarn",
  "country": "netherlands"
}
```

I can separate them out randomly during training data generation for the next batch though.

**Comment by mkaranta** [comment]
That explains that. 

I made most of the NL test cases using https://github.com/openvenues/address-formatting which introduced the space into the addresses (it was infrequently present before):
```
# Netherlands
NL:
    address_template: *generic1
    postformat_replace:
        # fix the postcode to make it \d\d\d\d \w\w
        - ["\n(\\d{4})(\\w{2}) ","\n$1 $2 "]
        - ["\nKoninkrijk der Nederlanden$","\nNederland"]
```

I was under the impression that libpostal was trained on a subset of addresses formatted using this formatter, but perhaps I am wrong.
