### ISSUE TITLE
extending parser rules addresses/de.yaml

### ISSUE THREAD

**Issue by nicslos** [openvenues/libpostal#315]
Hi,
I have tried to extend some parsing rules for de to be able to parse terminal/ebene as a unit.
Added the following to the file:
```
terminal: &terminal
        canonical: terminal
        sample: true
        canonical_probability: 0.7
        sample_probability: 0.3
        numeric:
            direction: left
        # Terminal 1
        add_number_phrase: true
        add_number_phrase_probability: 0.2
````

But was running make install again, but seems to have no effect.
What I'm doing wrong?

Thx
N
